imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CronkdBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: ~
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: cronkd
        connections:
            cronkd:
                driver: pdo_mysql
                host: '%database_host%'
                port: '%database_port%'
                dbname: '%database_name%'
                user: '%database_user%'
                password: '%database_password%'
                charset: UTF8

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: CronkdBundle\Entity\User
    from_email:
        address: get@cron.kd
        sender_name: get.cron.kd

stof_doctrine_extensions:
    orm:
        cronkd:
            timestampable: true

cronkd:
    resource_types:
        - Population
        - Material
        - Building
    resources:
        Civilian:
            type: Population
            description: Base Population resource.  Used to gather materials, build housing, and train to become military
            initial: 25
            value: 1
            spoil_of_war: true
            action: ~
        Material:
            type: Material
            description: Base Material resource.
            initial: 10
            value: 0
            spoil_of_war: true
            action:
                verb: "Gather"
                description: Gathering 1 Material requires 1 Civilian and is spread over 8 Ticks
                inputs:
                    Civilian:
                        quantity: 1
                        requeue: true
                        queue_size: 8
                output:
                    quantity: 1
                    queue_size: 8
        Housing:
            type: Building
            description: Base Housing resource which holds 1 Civilian resources
            initial: 10
            value: 2
            capacity: 1
            spoil_of_war: true
            action:
                verb: "Build"
                description: Housing requires 1 Civilian each and consumes 1 Material each and is spread over 8 Ticks
                inputs:
                    Civilian:
                        quantity: 1
                        requeue: true
                        queue_size: 8
                    Material:
                        quantity: 1
                output:
                    quantity: 1
                    queue_size: 8
        Military:
            type: Population
            description: Military resource that provides 1 Attack
            initial: 0
            attack: 1
            defense: 1
            value: 2
            action:
                verb: "Train"
                description: Training of Military converts 1 Civilian each and is spread over 8 Ticks
                inputs:
                    Civilian:
                        quantity: 1
                output:
                    quantity: 1
                    queue_size: 8
        Hacker:
            type: Population
            description: Military resource that is used to spy on other Kingdoms
            initial: 0
            attack: 0
            defense: 0
            probe_power: 1
            value: 3
            action:
                verb: "Train"
                description: Training of Hackers converts 1 Civilian each and is spread over 8 Ticks
                inputs:
                    Military:
                        quantity: 1
                output:
                    quantity: 1
                    queue_size: 8
