imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        host: '%test_database_host%'
        port: '%test_database_port%'
        dbname: '%test_database_name%'
        user: '%test_database_user%'
        password: '%test_database_password%'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

monolog:
    handlers:
        slack_error:
            type:       stream
            path:       '%kernel.logs_dir%/%kernel.environment%.errors.log'
            level:      error
            channels:   ['!main']
        slack_log:
            type:       stream
            path:       '%kernel.logs_dir%/%kernel.environment%.important.log'
            level:      notice
            channels:   ['!main']