services:
    cronkd.tick:
        class: CronkdBundle\Service\TickService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.resource"
            - "@cronkd.manager.log"
            - "@event_dispatcher"
            - "@logger"
        tags:
            - { name: monolog.logger, channel: tick }

    cronkd.queue_populator:
        class: CronkdBundle\Service\QueuePopulator
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.service.probing:
        class: CronkdBundle\Service\ProbingService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.policy"
            - "@event_dispatcher"
            - "@cronkd.manager.log"

    cronkd.service.attacking:
        class: CronkdBundle\Service\AttackingService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@event_dispatcher"
            - "@cronkd.queue_populator"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.resource"
            - "@cronkd.manager.log"
            - "@cronkd.manager.policy"

    cronkd.service.graphing:
        class: CronkdBundle\Service\GraphingService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.resource"

    # Managers
    cronkd.manager.world:
        class: CronkdBundle\Manager\WorldManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@event_dispatcher"
        calls:
            - [setLogger, ["@logger"]]

    cronkd.manager.kingdom:
        class: CronkdBundle\Manager\KingdomManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.resource"
            - "@cronkd.manager.policy"
            - "@event_dispatcher"
        calls:
            - [setLogger, ["@logger"]]

    cronkd.manager.resource:
        class: CronkdBundle\Manager\ResourceManager
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.manager.log:
        class: CronkdBundle\Manager\LogManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@jms_serializer"

    cronkd.manager.policy:
        class: CronkdBundle\Manager\PolicyManager
        arguments:
            - "@doctrine.orm.default_entity_manager"

    # Listeners
    cronkd.listener.elo:
        class: CronkdBundle\Listener\EloListener
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - {name: kernel.event_listener, event: event.attack, method: onAttack}

    cronkd.listener.kingdom_cached_stats:
        class: CronkdBundle\Listener\KingdomCachedStatsListener
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.log"
        tags:
            - {name: kernel.event_listener, event: event.world_tick, method: onTick}
            - {name: kernel.event_listener, event: event.create_kingdom, method: onCreateKingdom}
            - {name: kernel.event_listener, event: event.action, method: onAction}
            - {name: kernel.event_listener, event: event.attack, method: onAttack}

    cronkd.listener.notification:
        class: CronkdBundle\Listener\NotificationsListener
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - {name: kernel.event_listener, event: event.view_notifications, method: onViewNotificationsPage}

    cronkd.listener.resource:
        class: CronkdBundle\Listener\ResourceListener
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.resource"
        tags:
            - {name: kernel.event_listener, event: event.create_kingdom, method: onCreateKingdom, priority: 100}

    cronkd.listener.world:
        class: CronkdBundle\Listener\WorldListener
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@event_dispatcher"
        tags:
            - {name: kernel.event_listener, event: event.initialize_world, method: onInitializeWorld}

    # Twig
    cronkd.twig_extension:
        class: CronkdBundle\Twig\CronkdExtension
        public: true
        tags:
            - { name: twig.extension }