services:
    cronkd.queue_populator:
        class: CronkdBundle\Service\QueuePopulator
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.manager.kingdom:
        class: CronkdBundle\Service\KingdomManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@cronkd.manager.resource"
        calls:
            - [setLogger, ["@logger"]]

    cronkd.manager.resource:
        class: CronkdBundle\Service\ResourceManager
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.manager.log:
        class: CronkdBundle\Service\LogManager
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.service.probing:
        class: CronkdBundle\Service\ProbingService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@event_dispatcher"
            - "@cronkd.manager.log"

    cronkd.service.attacking:
        class: CronkdBundle\Service\AttackingService
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@event_dispatcher"
            - "@cronkd.queue_populator"
            - "@cronkd.manager.kingdom"
            - "@cronkd.manager.resource"
            - "@cronkd.manager.log"

    cronkd.listener.net_worth:
        class: CronkdBundle\Listener\NetWorthListener
        arguments:
            - "@cronkd.manager.kingdom"
        tags:
            - {name: kernel.event_listener, event: event.world_tick, method: onTick}
            - {name: kernel.event_listener, event: event.create_kingdom, method: onCreateKingdom}
            - {name: kernel.event_listener, event: event.action, method: onAction}
            - {name: kernel.event_listener, event: event.probe, method: onProbe}
            - {name: kernel.event_listener, event: event.attack, method: onAttack}