services:
    cronkd.queue_populator:
        class: CronkdBundle\Service\QueuePopulator
        arguments:
            - "@doctrine.orm.default_entity_manager"

    cronkd.manager.kingdom:
        class: CronkdBundle\Service\KingdomManager
        arguments:
            - "@doctrine.orm.default_entity_manager"
        calls:
            - [setLogger, ["@logger"]]

    cronkd.service.probing:
        class: CronkdBundle\Service\ProbingService
        arguments:
            - "@doctrine.orm.default_entity_manager"