<?php

namespace CronkdBundle\Repository;

/**
 * AttackEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackEventRepository extends \Doctrine\ORM\EntityRepository
{
}
