<?php

namespace CronkdBundle\Repository;

/**
 * AttackLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttackLogRepository extends \Doctrine\ORM\EntityRepository
{
}
