<?php

namespace CronkdBundle\Repository;

/**
 * KingdomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingdomRepository extends \Doctrine\ORM\EntityRepository
{
}
