<?php

namespace CronkdBundle\Repository;

/**
 * NetWorthLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NetWorthLogRepository extends \Doctrine\ORM\EntityRepository
{
}
