<?php
namespace CronkdBundle\Repository;

use CronkdBundle\Entity\World;

/**
 * QueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCurrentByWorld(World $world)
    {
        $qb = $this->createQueryBuilder('q');
        $qb->join('q.kingdom', 'k');
        $qb->where('k.world = :world');
        $qb->andWhere('q.tick = :worldTick');
        $qb->setParameters([
            'world'     => $world,
            'worldTick' => $world->getTick(),
        ]);

        return $qb->getQuery()->getResult();
    }
}
