<?php

namespace CronkdBundle\Repository;

/**
 * WorldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorldRepository extends \Doctrine\ORM\EntityRepository
{
}
